---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/comments":
    post:
      summary: Creates a comment
      tags:
      - Comment
      parameters: []
      responses:
        '201':
          description: comment created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  required: true
                post_id:
                  type: integer
                  required: true
          application/xml:
            schema:
              type: object
              properties:
                text:
                  type: string
                  required: true
                post_id:
                  type: integer
                  required: true
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
